name: flutter_nearby_connections_example
description: Demonstrates how to use the flutter_nearby_connections plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  flutter:
    sdk: flutter
  flutter_nearby_connections:
    path: ../
  flutter_styled_toast: ^2.2.1
  flutter_udid: ^2.0.1

dev_dependencies:
  dart_lintz: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
